### PR TITLE
Fix processing of delayed datasets

### LINKED ISSUE #7: trollflow fails when satpy warns about "Delaying generation ... because of incompatible areas"
When a product needs resampling and satpy.scene reports "Delaying generation of ... because of incompatible areas" the trollflow-sat fails.

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run self.__target(*self.__args, **self.__kwargs)
  File "/software/pytroll/lib/python2.7/site-packages/trollflow_sat-0.8.0-py2.7.egg/trollflow_sat/satpy_writer.py", line 184, in run lcl.save_dataset(dataset_ids[i],
IndexError: list index out of range

Here https://github.com/pytroll/trollflow-sat/blob/master/trollflow_sat/satpy_resampler.py#L88 the dataset_ids as assigned to an empty list instead of the products name, like overview. This happens with GOES-16 eumetcast data where some channel have a slightly different projection coefficients and for overview product all channels needs to be resampled.

For AVHRR data this works fine as all channels have the same projection coefficients.

I don't have a suggestion for solution, but if I hardcode the https://github.com/pytroll/trollflow-sat/blob/master/trollflow_sat/satpy_resampler.py#L101 to:
lcl.info["dataset_ids"] = ['overview'] it works, so the dataset_ids list needs to contain the product name instead of an empty list.

### PR DESCRIPTION
**Pull request by pnuu**
This PR fixes #7.

Basically the fix is to resample everything that is loaded, and use product names from the config in saving the files instead of DatasetIDs.

### CODE REVIEW

**Comment by TAlonglong** [comment]
Hm, no sorry
It does not work. At least with my setup.
Could also be I messed things up when I merged your branch with my metno-develop branch
I will have some more look at it.

**Comment by TAlonglong** [comment]
I think my problem is here, or something here:
https://github.com/pytroll/trollflow-sat/blob/fix-delayed/trollflow_sat/satpy_resampler.py#L86
I do have a satproj area, but the GOES16 data area not equal for each channel, so its tricky

**Comment by pnuu** [comment]
Oh, right. Yeah, this is caused by the GOES-16 non-uniform sampling we get via Eumetcast. I believe the only solution is to do resampling, which is of course quite costly.

SatPy supports saving the resampling look-up tables, but unfortunately re-calculates them if there's even slight differences in the data masking. And as each of the channels have different extents, the disk usage will be quite high. It seems that the `precompute` kwarg is present in `satpy_resampler.py`, but `cache_dir` isn't. And IIRC SatPy didn't have the kwarg with that name anyways... I'll take a look at that in the near future! And create an issue to SatPy regarding cache-recalculations, if there's not one already.

**Comment by pnuu** [comment]
OK, I was lazy and added the missing "mask_area" kwarg to this PR branch. Which is the - already implemented - way around the mask differences and recalculations in SatPy.

**Pull request merged**
